### ISSUE TITLE
windows下文件名含有非法字符会报错

### ISSUE THREAD

**Issue by Nefurenn** [tyokyo320/bilibili-downloader#14]
例如在#11 中提到的下载 BV1kV4y197Pt 这个视频

会有下面的报错

```
文艺复兴ε(*･ω･)_-ﾟ:･☆
下载的视频清晰度：高清 720P
开始下载视频： 文艺复兴ε(*･ω･)_-ﾟ:･☆.mp4
Traceback (most recent call last):
  File "D:\workplace\py_workplace\bilibili-downloader\main.py", line 41, in <module>
    main()
  File "D:\workplace\py_workplace\bilibili-downloader\main.py", line 29, in main
    b.download(config.URL)
  File "D:\workplace\py_workplace\bilibili-downloader\main.py", line 19, in download
    self.downloader.download_video(video)
  File "D:\workplace\py_workplace\bilibili-downloader\strategy\bilibili_executor.py", line 84, in download_video
    self._download(video_url, os.path.join(self.temp_path, video_filename))
  File "D:\workplace\py_workplace\bilibili-downloader\strategy\bilibili_executor.py", line 96, in _download
    with open(os.path.join(self.temp_path, filename), mode='wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'D:\\workplace\\py_workplace\\bilibili-downloader\\temp\\文艺复兴ε(*･ω･)_-ﾟ:･☆.mp4'
```

**Comment by Nefurenn** [comment]
非法字符包含了`<>:"/\|?*`

阅读源码后发现
https://github.com/tyokyo320/bilibili-downloader/blob/ccba4e0ea6b7a7bdf67a5fd35db42e5ef7ee8539/strategy/default.py#L48-L53

这里对`/`进行了处理

提的pr里面把处理代码放到了这个函数里
https://github.com/tyokyo320/bilibili-downloader/blob/ccba4e0ea6b7a7bdf67a5fd35db42e5ef7ee8539/models/video.py#L7

请问这部分代码放哪里比较合适，不对的话我再修改一下

**Comment by aaron9610** [comment]
@Nefurenn 感谢问题反馈！
我刚测试了一下，确实 windows 下面会出现这个问题（linux 环境下是正常的所以之前忽略这个 issue 了），之前写的时候想让 `Video` 类尽可能简洁，所以把逻辑处理部分都放在了 `get_video_title()`  下面了。因为爬取一般视频的逻辑都在 `DefaultStrategy` 下面。
