### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by aaron9610** [tyokyo320/bilibili-downloader#3]
## :moyai: 概要

由于更新导致下载收藏夹合集URL时无法获取视频标题

```python
$ python main.py

Traceback (most recent call last):
  File "/home/users/work/repos/bilibili-downloader/main.py", line 50, in <module>
    main()
  File "/home/users/work/repos/bilibili-downloader/main.py", line 28, in main
    b.download([
  File "/home/users/work/repos/bilibili-downloader/main.py", line 17, in download
    video = self.crawler.get(url)
  File "/home/users/work/repos/bilibili-downloader/strategy/bilibili_executor.py", line 42, in get
    video = strategy.get(video)
  File "/home/users/work/repos/bilibili-downloader/strategy/default.py", line 50, in get
    title = self.get_video_title(bs)
  File "/home/users/work/repos/bilibili-downloader/strategy/default.py", line 32, in get_video_title
    video_title = bs.find('h1 title').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by limedon** [comment]
在下载纪录片的时候遇到相同的问题了
